variable "env" {}
variable "vpc" {}
variable "default_vpc_id" {}
variable "docdb" {}
variable "rds" {}
variable "elasticache" {}
variable "rabbitmq" {}
#variable "internet_gw" {}
#variable "nat_gw" {}